export const archive = [
  {
    "Full Name": "Danny Sermon",
    "First Name": "Danny",
    "Last Name": "Sermon",
    "Charge": "First degree",
    "Interview": "7/10/2017",
    "DOB": "08/06/1954",
    "Ethnicity": "WM",
    "Offense date": "09/05/1977",
    "Age at offense": "23",
    "Time served at interview": "39 years",
    "Id": "96106",
    "At launch": "",
    "Include": "",
    "Notes": "Codefendant tried separately George Herbert English http://law.justia.com/cases/louisiana/supreme-court/1979/367-so-2d-815-1.html Runs veterans groups."
  },
  {
    "Full Name": "Ron Hicks",
    "First Name": "Ron",
    "Last Name": "Hicks",
    "Charge": "Second degree",
    "Interview": "7/10/2017",
    "DOB": "06/30/1970",
    "Ethnicity": "BM",
    "Offense date": "02/01/1990",
    "Age at offense": "19",
    "Time served at interview": "27 years",
    "Id": "291928",
    "At launch": "",
    "Include": "",
    "Notes": "Denied clemency."
  },
  {
    "Full Name": "Manuel Nelson",
    "First Name": "Manuel",
    "Last Name": "Nelson",
    "Charge": "Second degree 2 counts",
    "Interview": "7/10/2017",
    "DOB": "08/19/1970",
    "Ethnicity": "BM",
    "Offense date": "07/10/1994 and 07/16/94",
    "Age at offense": "23",
    "Time served at interview": "23 years",
    "Id": "128881",
    "At launch": "",
    "Include": "",
    "Notes": "Codefendant Lawrence Peters sentenced to life http://caselaw.findlaw.com/la-court-of-appeal/1042959.html"
  },
  {
    "Full Name": "Jerry Lewis",
    "First Name": "Jerry",
    "Last Name": "Lewis",
    "Charge": "Second degree",
    "Interview": "7/10/2017",
    "DOB": "01/16/1959",
    "Ethnicity": "BM",
    "Offense date": "01/01/1980",
    "Age at offense": "20",
    "Time served at interview": "37 years",
    "Id": "104544",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19851141482So2d659_1975/STATE v. LEWISDeclined manslaughter plea, charged with 2nd degree. Offense just past the 73-79 relief."
  },
  {
    "Full Name": "Merlin Renard",
    "First Name": "Merlin",
    "Last Name": "Renard",
    "Charge": "Second degree",
    "Interview": "7/11/2017",
    "DOB": "07/17/1959",
    "Ethnicity": "BM",
    "Offense date": "04/30/1978",
    "Age at offense": "18",
    "Time served at interview": "39 years",
    "Id": "118111",
    "At launch": "",
    "Include": "",
    "Notes": "Codefendant Wayne D. Thomas sentenced to life for second degree http://www.leagle.com/decision/19941909637So2d1272_11372/STATE v. THOMAS Relief 1973-1979 Second degree parole eligibility.Parole hearing scheduled 12/17/19."
  },
  {
    "Full Name": "Hannibal Stanfield",
    "First Name": "Hannibal",
    "Last Name": "Stanfield",
    "Charge": "First degree",
    "Interview": "7/11/2017",
    "DOB": "12/22/1968",
    "Ethnicity": "BM",
    "Offense date": "11/05/1988",
    "Age at offense": "19",
    "Time served at interview": "28 years",
    "Id": "127639",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19901531562So2d969_11478/STATE v. STANFIELD"
  },
  {
    "Full Name": "Ernest McGee",
    "First Name": "Ernest",
    "Last Name": "McGee",
    "Charge": "Second degree",
    "Interview": "7/11/2017",
    "DOB": "09/03/1959",
    "Ethnicity": "BM",
    "Offense date": "04/30/1978",
    "Age at offense": "18",
    "Time served at interview": "39 years",
    "Id": "98665",
    "At launch": "",
    "Include": "",
    "Notes": "Granted parole eligibility after 42 years on June 5, 2017 http://www.leagle.com/decision/19861809491So2d1318_11565/STATE v. HAYWOOD"
  },
  {
    "Full Name": "Sherman Singleton",
    "First Name": "Sherman",
    "Last Name": "Singleton",
    "Charge": "Second degree",
    "Interview": "7/11/2017",
    "DOB": "08/28/1969",
    "Ethnicity": "BM",
    "Offense date": "08/08/1990",
    "Age at offense": "20",
    "Time served at interview": "26 years",
    "Id": "309680",
    "At launch": "",
    "Include": "",
    "Notes": "(Identified by Len Davis!)"
  },
  {
    "Full Name": "Theortric Givens",
    "First Name": "Theortric",
    "Last Name": "Givens",
    "Charge": "Second degree",
    "Interview": "7/17/2017",
    "DOB": "04/21/1951",
    "Ethnicity": "BM",
    "Offense date": "12/17/1975",
    "Age at offense": "24",
    "Time served at interview": "41 years",
    "Id": "83827",
    "At launch": "",
    "Include": "",
    "Notes": "Denied parole 5/17/2018."
  },
  {
    "Full Name": "Aaron Brent",
    "First Name": "Aaron",
    "Last Name": "Brent",
    "Charge": "Second degree",
    "Interview": "7/17/2017",
    "DOB": "02/20/1957",
    "Ethnicity": "BM",
    "Offense date": "04/23/1976",
    "Age at offense": "19",
    "Time served at interview": "41 years",
    "Id": "86847",
    "At launch": "",
    "Include": "",
    "Notes": "Paroled 6/5/2018."
  },
  {
    "Full Name": "Michael Doggett",
    "First Name": "Michael",
    "Last Name": "Doggett",
    "Charge": "First degree",
    "Interview": "7/17/2017",
    "DOB": "05/14/1954",
    "Ethnicity": "WM",
    "Offense date": "09/28/1978",
    "Age at offense": "24",
    "Time served at interview": "38 years",
    "Id": "90124",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Raymond Flank",
    "First Name": "Raymond",
    "Last Name": "Flank",
    "Charge": "First degree",
    "Interview": "7/17/2017",
    "DOB": "09/17/1961",
    "Ethnicity": "BM",
    "Offense date": "12/17/1983",
    "Age at offense": "22",
    "Time served at interview": "33 years",
    "Id": "110756",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/1988773537So2d236_1752/STATE v. FLANK"
  },
  {
    "Full Name": "Darren James",
    "First Name": "Darren",
    "Last Name": "James",
    "Charge": "First degree",
    "Interview": "7/17/2017",
    "DOB": "09/14/1964",
    "Ethnicity": "BM",
    "Offense date": "01/08/1987",
    "Age at offense": "22",
    "Time served at interview": "30 years",
    "Id": "120368",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.courtlistener.com/opinion/1816876/state-v-james/"
  },
  {
    "Full Name": "Arthur Carter",
    "First Name": "Arthur",
    "Last Name": "Carter",
    "Charge": "Second degree",
    "Interview": "7/18/2017",
    "DOB": "10/10/1963",
    "Ethnicity": "BM",
    "Offense date": "07/03/1988",
    "Age at offense": "24",
    "Time served at interview": "29 years",
    "Id": "125211",
    "At launch": "",
    "Include": "",
    "Notes": "Sentence commuted 6/18/2018 to 65 years with 37.5 to be served (less in reality). Bidish’s client."
  },
  {
    "Full Name": "William Hall",
    "First Name": "William",
    "Last Name": "Hall",
    "Charge": "First degree",
    "Interview": "7/18/2017",
    "DOB": "05/09/1969",
    "Ethnicity": "WM",
    "Offense date": "10/15/1988",
    "Age at offense": "19 (Death Row)",
    "Time served at interview": "28 years",
    "Id": "129456",
    "At launch": "",
    "Include": "",
    "Notes": "Granted a hearing, no date."
  },
  {
    "Full Name": "Jeffrey Hilburn",
    "First Name": "Jeffrey",
    "Last Name": "Hilburn",
    "Charge": "Second degree",
    "Interview": "7/18/2017",
    "DOB": "01/03/1967",
    "Ethnicity": "WM",
    "Offense date": "06/12/1991",
    "Age at offense": "24",
    "Time served at interview": "26 years",
    "Id": "319221",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/1993860625So2d235_1741/STATE v. HILBURN"
  },
  {
    "Full Name": "Tommy Floyd",
    "First Name": "Tommy",
    "Last Name": "Floyd",
    "Charge": "Second degree",
    "Interview": "7/24/2017",
    "DOB": "09/29/1974",
    "Ethnicity": "WM",
    "Offense date": "08/05/1994",
    "Age at offense": "19",
    "Time served at interview": "24 years",
    "Id": "326105",
    "At launch": "",
    "Include": "",
    "Notes": "Trusty off Farm"
  },
  {
    "Full Name": "Terence Guy",
    "First Name": "Terence",
    "Last Name": "Guy",
    "Charge": "Second degree",
    "Interview": "7/24/2017",
    "DOB": "06/14/1973",
    "Ethnicity": "BM",
    "Offense date": "02/07/1994",
    "Age at offense": "20",
    "Time served at interview": "23 years",
    "Id": "347725",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.courtlistener.com/opinion/1142198/state-v-guy/"
  },
  {
    "Full Name": "Walter Goodwin",
    "First Name": "Walter",
    "Last Name": "Goodwin",
    "Charge": "Second degree",
    "Interview": "7/24/2017",
    "DOB": "05/05/1974",
    "Ethnicity": "BM",
    "Offense date": "04/11/1994",
    "Age at offense": "19",
    "Time served at interview": "23 years",
    "Id": "356166",
    "At launch": "",
    "Include": "",
    "Notes": "http://caselaw.findlaw.com/la-court-of-appeal/1465824.html"
  },
  {
    "Full Name": "Julius Holden",
    "First Name": "Julius",
    "Last Name": "Holden",
    "Charge": "Second degree",
    "Interview": "7/24/2017",
    "DOB": "08/13/1971",
    "Ethnicity": "WM",
    "Offense date": "02/01/1995",
    "Age at offense": "23",
    "Time served at interview": "22 years",
    "Id": "360323",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Jimmy Robinson",
    "First Name": "Jimmy",
    "Last Name": "Robinson",
    "Charge": "First degree",
    "Interview": "7/25/2017",
    "DOB": "08/16/1956",
    "Ethnicity": "BM",
    "Offense date": "08/05/1980",
    "Age at offense": "23",
    "Time served at interview": "36 years",
    "Id": "99596",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.courtlistener.com/opinion/1798184/state-v-robinson/ Pardon hearing 12/16/19"
  },
  {
    "Full Name": "Archie Tyner",
    "First Name": "Archie",
    "Last Name": "Tyner",
    "Charge": "First degree",
    "Interview": "7/25/2017",
    "DOB": "07/30/1966",
    "Ethnicity": "WM",
    "Offense date": "06/02/1986",
    "Age at offense": "19",
    "Time served at interview": "31 years",
    "Id": "113458",
    "At launch": "",
    "Include": "",
    "Notes": "Granted clemency hearing 12/16/19"
  },
  {
    "Full Name": "Everett Offray",
    "First Name": "Everett",
    "Last Name": "Offray",
    "Charge": "Second degree",
    "Interview": "7/25/2017",
    "DOB": "04/15/1976",
    "Ethnicity": "BM",
    "Offense date": "07/13/1994",
    "Age at offense": "18",
    "Time served at interview": "23 years",
    "Id": "369965",
    "At launch": "",
    "Include": "",
    "Notes": "http://caselaw.findlaw.com/la-court-of-appeal/1263949.html"
  },
  {
    "Full Name": "Charles Amos",
    "First Name": "Charles",
    "Last Name": "Amos",
    "Charge": "Second degree",
    "Interview": "7/27/2017",
    "DOB": "05/17/1973",
    "Ethnicity": "BM",
    "Offense date": "07/13/1993",
    "Age at offense": "20",
    "Time served at interview": "24 years",
    "Id": "130187",
    "At launch": "",
    "Include": "",
    "Notes": "Clemency hearing date: 9/17/2018 GRANTED Parole after 30"
  },
  {
    "Full Name": "Surge Sherman",
    "First Name": "Surge",
    "Last Name": "Sherman",
    "Charge": "Second degree",
    "Interview": "7/27/2017",
    "DOB": "08/22/1972",
    "Ethnicity": "BM",
    "Offense date": "06/29/1991",
    "Age at offense": "18",
    "Time served at interview": "26 years",
    "Id": "324413",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/1993951630So2d321_1921/STATE%20v.%20SHERMAN"
  },
  {
    "Full Name": "Roderick Sneed",
    "First Name": "Roderick",
    "Last Name": "Sneed",
    "Charge": "First degree",
    "Interview": "7/27/2017",
    "DOB": "12/23/1974",
    "Ethnicity": "BM",
    "Offense date": "08/15/1997",
    "Age at offense": "22",
    "Time served at interview": "19 years",
    "Id": "405050",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.iberianet.com/grand-jury-indicts-in-carjacking-murdercarissa-hebert-the-daily-iberian/article_422d93ec-4c90-5384- abe5-046694ac66f6.htmlCodefendant is Jason Baudoin"
  },
  {
    "Full Name": "Monte White",
    "First Name": "Monte",
    "Last Name": "White",
    "Charge": "First degree",
    "Interview": "7/27/2017",
    "DOB": "01/26/1975",
    "Ethnicity": "BM",
    "Offense date": "07/22/1997",
    "Age at offense": "22",
    "Time served at interview": "20 years",
    "Id": "334605",
    "At launch": "",
    "Include": "",
    "Notes": "http://law.justia.com/cases/louisiana/fourth-circuit-court-of-appeal/2001/2000-ka-1740.html"
  },
  {
    "Full Name": "Darwin Willie",
    "First Name": "Darwin",
    "Last Name": "Willie",
    "Charge": "Second degree",
    "Interview": "7/28/2017",
    "DOB": "07/18/1977",
    "Ethnicity": "WM",
    "Offense date": "10/12/1995",
    "Age at offense": "18",
    "Time served at interview": "21 years",
    "Id": "393184",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Daryl Waters",
    "First Name": "Daryl",
    "Last Name": "Waters",
    "Charge": "Second degree",
    "Interview": "7/28/2017",
    "DOB": "05/26/1968",
    "Ethnicity": "BM",
    "Offense date": "02/09/1992",
    "Age at offense": "23",
    "Time served at interview": "25 years",
    "Id": "366401",
    "At launch": "",
    "Include": "",
    "Notes": "Dealing drugs in Gibson, LAPARDON HEARING 4/15/2018 GRANTED IPE"
  },
  {
    "Full Name": "John Sheehan",
    "First Name": "John",
    "Last Name": "Sheehan",
    "Charge": "Second degree",
    "Interview": "7/28/2017",
    "DOB": "02/19/1965",
    "Ethnicity": "WM",
    "Offense date": "04/30/1986",
    "Age at offense": "21",
    "Time served at interview": "31 years",
    "Id": "116199",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19871185515So2d670_11071"
  },
  {
    "Full Name": "Lawson Strickland",
    "First Name": "Lawson",
    "Last Name": "Strickland",
    "Charge": "First degree",
    "Interview": "7/28/2017",
    "DOB": "07/26/1970",
    "Ethnicity": "WM",
    "Offense date": "11/03/1992",
    "Age at offense": "",
    "Time served at interview": "24 years",
    "Id": "328849",
    "At launch": "",
    "Include": "",
    "Notes": "(Escaped Death Row) https://www.leagle.com/decision/1996901683so2d2181900"
  },
  {
    "Full Name": "Sammie Robinson",
    "First Name": "Sammie",
    "Last Name": "Robinson",
    "Charge": "First degree",
    "Interview": "7/31/2017",
    "DOB": "01/06/1936",
    "Ethnicity": "BM",
    "Offense date": "10/02/1957 but came to Angola in 1953 (1957 was murder at Angola when he was 21)",
    "Age at offense": "17 (attempted aggravated rape of a woman in Rapides parish – 15 year sentence)",
    "Time served at interview": "63 years",
    "Id": "78589",
    "At launch": "",
    "Include": "",
    "Notes": "http://law.justia.com/cases/louisiana/supreme-court/1979/367-so-2d-360-1.htmlLongest serving man in Louisiana (first incarcerated in juvenile facility at 15 in 1951)"
  },
  {
    "Full Name": "Charles Unger",
    "First Name": "Charles",
    "Last Name": "Unger",
    "Charge": "First degree",
    "Interview": "7/31/2017",
    "DOB": "10/01/1959",
    "Ethnicity": "WM",
    "Offense date": "05/21/1977",
    "Age at offense": "17",
    "Time served at interview": "40 years",
    "Id": "87945",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19781457362So2d1095_11224/STATE%20v.%20UNGERPAROLED IN NOVEMBER 16 2017 (Under 70’s lifer rule)"
  },
  {
    "Full Name": "Troy West",
    "First Name": "Troy",
    "Last Name": "West",
    "Charge": "First degree",
    "Interview": "7/31/2017",
    "DOB": "05/16/1973",
    "Ethnicity": "BM",
    "Offense date": "08/05/1993",
    "Age at offense": "20",
    "Time served at interview": "23 years",
    "Id": "311719",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19961214669so2d54511015 https://www.leagle.com/decision/19971975688so2d128711666 Codefendant Steve Evans"
  },
  {
    "Full Name": "Kuantau Reeder",
    "First Name": "Kuantau",
    "Last Name": "Reeder",
    "Charge": "Second degree",
    "Interview": "7/31/2017",
    "DOB": "09/10/1972",
    "Ethnicity": "BM",
    "Offense date": "04/13/1993",
    "Age at offense": "20",
    "Time served at interview": "24 years",
    "Id": "229613",
    "At launch": "",
    "Include": "",
    "Notes": "(Tulane case Katherine’s client) http://caselaw.findlaw.com/la-court-of-appeal/1240304.html"
  },
  {
    "Full Name": "Jack Segura",
    "First Name": "Jack",
    "Last Name": "Segura",
    "Charge": "Second degree",
    "Interview": "7/28/2017",
    "DOB": "02/09/1964",
    "Ethnicity": "WM",
    "Offense date": "04/24/1982",
    "Age at offense": "18",
    "Time served at interview": "35 years",
    "Id": "101469",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19851580464So2d1116_11334/STATE%20v.%20SEGURA"
  },
  {
    "Full Name": "Shawn Gaspard",
    "First Name": "Shawn",
    "Last Name": "Gaspard",
    "Charge": "First degree",
    "Interview": "8/7/2017",
    "DOB": "09/18/1968",
    "Ethnicity": "WM",
    "Offense date": "10/02/1992",
    "Age at offense": "24",
    "Time served at interview": "24 years",
    "Id": "125280",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19991471746So2d725_11347/STATE%20v.%20GASPARD"
  },
  {
    "Full Name": "Terry Pierce",
    "First Name": "Terry",
    "Last Name": "Pierce",
    "Charge": "Second degree",
    "Interview": "8/7/2017",
    "DOB": "09/27/1957",
    "Ethnicity": "BM",
    "Offense date": "07/05/1980",
    "Age at offense": "22",
    "Time served at interview": "37 years",
    "Id": "98771",
    "At launch": "",
    "Include": "",
    "Notes": "https://casetext.com/case/state-v-pierce-113DENIED A HEARING BY PARDON BOARD IN OCTOBER 2017 – Spiraled after"
  },
  {
    "Full Name": "Walter Reed",
    "First Name": "Walter",
    "Last Name": "Reed",
    "Charge": "First degree",
    "Interview": "8/7/2017",
    "DOB": "11/14/1952",
    "Ethnicity": "BM",
    "Offense date": "09/30/1974",
    "Age at offense": "21",
    "Time served at interview": "42 years",
    "Id": "87051",
    "At launch": "",
    "Include": "",
    "Notes": "DIED OF LUNG CANCER IN 2018."
  },
  {
    "Full Name": "Ron Wiggins",
    "First Name": "Ron",
    "Last Name": "Wiggins",
    "Charge": "Second degree",
    "Interview": "8/7/2017",
    "DOB": "12/17/1963",
    "Ethnicity": "BM",
    "Offense date": "02/16/1986",
    "Age at offense": "22",
    "Time served at interview": "31 years",
    "Id": "116792",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19871061518So2d543_11026/STATE%20v.%20WIGGINSPARDON HEARING 10/15/2018. REMOVED FOR DISCIPLINARY. Transferred to Hunt."
  },
  {
    "Full Name": "Allen Pharr",
    "First Name": "Allen",
    "Last Name": "Pharr",
    "Charge": "Second degree",
    "Interview": "8/7/2017",
    "DOB": "04/28/1964",
    "Ethnicity": "BM",
    "Offense date": "04/26/1987",
    "Age at offense": "22",
    "Time served at interview": "30 years",
    "Id": "122731",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Norman Dozier",
    "First Name": "Norman",
    "Last Name": "Dozier",
    "Charge": "",
    "Interview": "8/8/2017",
    "DOB": "08/26/1971",
    "Ethnicity": "BM",
    "Offense date": "01/10/1996",
    "Age at offense": "24",
    "Time served at interview": "21 years",
    "Id": "387320",
    "At launch": "",
    "Include": "",
    "Notes": "http://caselaw.findlaw.com/la-court-of-appeal/1308130.html Codefendant Winfred Davenport.Granted hearing. No date."
  },
  {
    "Full Name": "Jarrod Lanclow",
    "First Name": "Jarrod",
    "Last Name": "Lanclow",
    "Charge": "Second degree",
    "Interview": "8/8/2017",
    "DOB": "07/26/1977",
    "Ethnicity": "WM",
    "Offense date": "01/27/1996",
    "Age at offense": "18",
    "Time served at interview": "21 years",
    "Id": "376336",
    "At launch": "",
    "Include": "",
    "Notes": "GRANTED HEARING. No date."
  },
  {
    "Full Name": "Paul Mayho",
    "First Name": "Paul",
    "Last Name": "Mayho",
    "Charge": "Second degree",
    "Interview": "8/8/2017",
    "DOB": "08/22/1966",
    "Ethnicity": "BM",
    "Offense date": "07/12/1989",
    "Age at offense": "22",
    "Time served at interview": "28 years",
    "Id": "298479",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19921384601So2d783_11314/STATE%20v.%20MAYHOPARDON HEARING MADE PAROLE ELIGIBLE AFTER SERVING 40 years"
  },
  {
    "Full Name": "Tommy Cage",
    "First Name": "Tommy",
    "Last Name": "Cage",
    "Charge": "First degree",
    "Interview": "8/14/2017",
    "DOB": "09/12/1966",
    "Ethnicity": "BM",
    "Offense date": "04/06/1986",
    "Age at offense": "19",
    "Time served at interview": "31 years",
    "Id": "120587",
    "At launch": "",
    "Include": "",
    "Notes": "http://law.justia.com/cases/louisiana/supreme-court/1991/583-so-2d-1125-1.html"
  },
  {
    "Full Name": "Hayward Jones",
    "First Name": "Hayward",
    "Last Name": "Jones",
    "Charge": "Second degree",
    "Interview": "8/14/2017",
    "DOB": "10/17/1973",
    "Ethnicity": "BM",
    "Offense date": "06/09/1997",
    "Age at offense": "23",
    "Time served at interview": "20 years",
    "Id": "394685",
    "At launch": "",
    "Include": "",
    "Notes": "(71 year old man killed in burglary - had a heart attack) At HuntDenied 1-4 by board February 2017"
  },
  {
    "Full Name": "Terry West",
    "First Name": "Terry",
    "Last Name": "West",
    "Charge": "First degree",
    "Interview": "8/14/2017",
    "DOB": "02/16/1975",
    "Ethnicity": "BM",
    "Offense date": "12/24/1995",
    "Age at offense": "20",
    "Time served at interview": "21 years",
    "Id": "396701",
    "At launch": "",
    "Include": "",
    "Notes": "Codefendant Troy Andrews"
  },
  {
    "Full Name": "James Refuge",
    "First Name": "James",
    "Last Name": "Refuge",
    "Charge": "First degree",
    "Interview": "8/15/2017",
    "DOB": "02/15/1951",
    "Ethnicity": "BM",
    "Offense date": "11/29/1969",
    "Age at offense": "18",
    "Time served at interview": "47 years",
    "Id": "74358",
    "At launch": "",
    "Include": "",
    "Notes": "(Death Row) https://law.justia.com/cases/louisiana/supreme-court/1972/264-la-135-1.html"
  },
  {
    "Full Name": "Jimmy Williams",
    "First Name": "Jimmy",
    "Last Name": "Williams",
    "Charge": "",
    "Interview": "8/15/2017",
    "DOB": "12/09/1975",
    "Ethnicity": "BM",
    "Offense date": "06/15/1994",
    "Age at offense": "18",
    "Time served at interview": "23 years",
    "Id": "329477",
    "At launch": "",
    "Include": "",
    "Notes": "(Death row) http://caselaw.findlaw.com/la-supreme-court/1011836.html"
  },
  {
    "Full Name": "Edbert Simmons",
    "First Name": "Edbert",
    "Last Name": "Simmons",
    "Charge": "Second degree",
    "Interview": "8/15/2017",
    "DOB": "08/03/1963",
    "Ethnicity": "BM",
    "Offense date": "11/05/1981",
    "Age at offense": "18",
    "Time served at interview": "35 years",
    "Id": "104311",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/1985736465So2d271_1661/STATE%20v.%20WIGGINSGranted hearing, no date. Has an attorney."
  },
  {
    "Full Name": "Sidney Anderson",
    "First Name": "Sidney",
    "Last Name": "Anderson",
    "Charge": "Second degree",
    "Interview": "8/14/2017",
    "DOB": "02/13/1974",
    "Ethnicity": "BM",
    "Offense date": "11/20/1993",
    "Age at offense": "19",
    "Time served at interview": "23 years",
    "Id": "358404",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.leagle.com/decision/19971027691So2d336_1885/STATE%20v.%20ANDERSONDenied by pardon board October 2019. Bidish’s Client."
  },
  {
    "Full Name": "Vashon Kelly",
    "First Name": "Vashon",
    "Last Name": "Kelly",
    "Charge": "Second degree",
    "Interview": "8/17/2017",
    "DOB": "04/04/1974",
    "Ethnicity": "BM",
    "Offense date": "08/06/1994",
    "Age at offense": "20",
    "Time served at interview": "23 years",
    "Id": "367803",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1043101.html"
  },
  {
    "Full Name": "Keith Morse",
    "First Name": "Keith",
    "Last Name": "Morse",
    "Charge": "First degree",
    "Interview": "8/17/2017",
    "DOB": "03/25/1975",
    "Ethnicity": "BM",
    "Offense date": "07/01/1994",
    "Age at offense": "19",
    "Time served at interview": "23 years",
    "Id": "355646",
    "At launch": "",
    "Include": "",
    "Notes": "PARDON BOARD DATE: 9/17/2018 GRANTED IMMEDIATELY. Victim support. Wife: Kristen Morse"
  },
  {
    "Full Name": "Kevin King",
    "First Name": "Kevin",
    "Last Name": "King",
    "Charge": "Second degree",
    "Interview": "6/13/2018",
    "DOB": "03/13/1971",
    "Ethnicity": "BM",
    "Offense date": "04/05/1990",
    "Age at offense": "19",
    "Time served at interview": "28 years",
    "Id": "297826",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Layla Roberts",
    "First Name": "Layla",
    "Last Name": "Roberts",
    "Charge": "Aggravated kidnapping",
    "Interview": "6/14/2018",
    "DOB": "11/01/1976",
    "Ethnicity": "BM",
    "Offense date": "09/26/1995",
    "Age at offense": "18",
    "Time served at interview": "22 years",
    "Id": "383670",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1307676.html 9/13/2017 PARDON BOARD GIVEN 99 WITH PE AFTER 25"
  },
  {
    "Full Name": "Lawrence Kelly",
    "First Name": "Lawrence",
    "Last Name": "Kelly",
    "Charge": "First degree",
    "Interview": "6/14/2018",
    "DOB": "03/26/1974",
    "Ethnicity": "BM",
    "Offense date": "03/29/1992",
    "Age at offense": "18 (3 days into 18)",
    "Time served at interview": "26 years",
    "Id": "343052",
    "At launch": "",
    "Include": "",
    "Notes": "(Inmate counsel)https://www.leagle.com/decision/19951739661so2d107811477 Innocence claim"
  },
  {
    "Full Name": "Darryl Evans",
    "First Name": "Darryl",
    "Last Name": "Evans",
    "Charge": "Second degree",
    "Interview": "6/20/2018",
    "DOB": "10/14/1960",
    "Ethnicity": "BM",
    "Offense date": "03/30/1983",
    "Age at offense": "22",
    "Time served at interview": "35 years",
    "Id": "110220",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19851136463so2d67311013 PARDON BOARD 7/23/2018 DENIED – “Nature of crime”"
  },
  {
    "Full Name": "Keith Byes",
    "First Name": "Keith",
    "Last Name": "Byes",
    "Charge": "Second degree",
    "Interview": "6/20/2018",
    "DOB": "05/21/1964",
    "Ethnicity": "BM",
    "Offense date": "04/06/1987",
    "Age at offense": "22",
    "Time served at interview": "31 years",
    "Id": "120720",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1028108.html PARDON BOARD 7/23/2018. DENIED- Victim opposition"
  },
  {
    "Full Name": "Mingo Javery",
    "First Name": "Mingo",
    "Last Name": "Javery",
    "Charge": "Second degree",
    "Interview": "6/22/2018",
    "DOB": "02/02/1974",
    "Ethnicity": "BM",
    "Offense date": "02/12/1992",
    "Age at offense": "18 (10 days after 18)",
    "Time served at interview": "18 years",
    "Id": "326208",
    "At launch": "",
    "Include": "",
    "Notes": "(Was apprehended years later in 2000)"
  },
  {
    "Full Name": "Darnell Craft",
    "First Name": "Darnell",
    "Last Name": "Craft",
    "Charge": "Second degree",
    "Interview": "6/22/2018",
    "DOB": "03/28/1977",
    "Ethnicity": "BM",
    "Offense date": "05/27/1995",
    "Age at offense": "18",
    "Time served at interview": "23 years",
    "Id": "362608",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Bernell Juluke",
    "First Name": "Bernell",
    "Last Name": "Juluke",
    "Charge": "Second degree",
    "Interview": "6/22/2018",
    "DOB": "07/17/1976",
    "Ethnicity": "BM",
    "Offense date": "08/22/1994",
    "Age at offense": "18",
    "Time served at interview": "21 years",
    "Id": "388921",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-supreme-court/1430537.html Innocence claim; Len Davis"
  },
  {
    "Full Name": "Robert Juarbe",
    "First Name": "Robert",
    "Last Name": "Juarbe",
    "Charge": "Second degree",
    "Interview": "6/27/2018",
    "DOB": "08/31/1973",
    "Ethnicity": "BM",
    "Offense date": "11/16/1994",
    "Age at offense": "20",
    "Time served at interview": "22 years",
    "Id": "303486",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1228118.htmlPARDON BOARD 9/17/2018 DENIED – Denied his role in the crime; backfired"
  },
  {
    "Full Name": "Chris Montague",
    "First Name": "Chris",
    "Last Name": "Montague",
    "Charge": "Second degree",
    "Interview": "6/27/2018",
    "DOB": "11/10/1969",
    "Ethnicity": "BM",
    "Offense date": "06/11/1990?",
    "Age at offense": "24",
    "Time served at interview": "28 years",
    "Id": "198497",
    "At launch": "",
    "Include": "",
    "Notes": "PARDON BOARD 9/17/2018 DENIED – Jones Acknowledged he was principal, but “Not enough time; GED”"
  },
  {
    "Full Name": "Marcus Artis",
    "First Name": "Marcus",
    "Last Name": "Artis",
    "Charge": "Second degree",
    "Interview": "7/17/2018",
    "DOB": "01/03/1977",
    "Ethnicity": "BM",
    "Offense date": "07/23/1995",
    "Age at offense": "18",
    "Time served at interview": "22 years",
    "Id": "361755",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.fundedjustice.com/a1LXu7?ref=ab_9Q5vZi2pTFA9Q5vZi2pTFA Innocence claim"
  },
  {
    "Full Name": "Adonis Brooks",
    "First Name": "Adonis",
    "Last Name": "Brooks",
    "Charge": "Second degree",
    "Interview": "7/17/2018",
    "DOB": "01/22/1974",
    "Ethnicity": "BM",
    "Offense date": "04/22/1992",
    "Age at offense": "18",
    "Time served at interview": "26 years",
    "Id": "323763",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1072224.html Innocence claim"
  },
  {
    "Full Name": "Kenneth Hill",
    "First Name": "Kenneth",
    "Last Name": "Hill",
    "Charge": "First degree",
    "Interview": "7/17/2018",
    "DOB": "12/17/1971",
    "Ethnicity": "BM",
    "Offense date": "06/26/1990",
    "Age at offense": "18",
    "Time served at interview": "28 years",
    "Id": "318876",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Anthony Hingle",
    "First Name": "Anthony",
    "Last Name": "Hingle",
    "Charge": "Second degree",
    "Interview": "7/17/2018",
    "DOB": "12/23/1969",
    "Ethnicity": "BM",
    "Offense date": "09/03/1988",
    "Age at offense": "18",
    "Time served at interview": "29 years",
    "Id": "131049",
    "At launch": "",
    "Include": "",
    "Notes": "9/13/17 Granted parole eligibility after 35 years on fixed term of 99. But then revoked due to disciplinary issues in April 2018."
  },
  {
    "Full Name": "Gregory Alcindor",
    "First Name": "Gregory",
    "Last Name": "Alcindor",
    "Charge": "First degree",
    "Interview": "7/18/2018",
    "DOB": "08/31/1968",
    "Ethnicity": "BM",
    "Offense date": "02/11/1987",
    "Age at offense": "18",
    "Time served at interview": "31 years",
    "Id": "119887",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Jerry Brown",
    "First Name": "Jerry",
    "Last Name": "Brown",
    "Charge": "Second degree",
    "Interview": "7/18/2018",
    "DOB": "09/01/1976",
    "Ethnicity": "BM",
    "Offense date": "06/16/1995",
    "Age at offense": "18",
    "Time served at interview": "23 years",
    "Id": "414849",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1285739.html"
  },
  {
    "Full Name": "Alvin Catchings",
    "First Name": "Alvin",
    "Last Name": "Catchings",
    "Charge": "Second degree",
    "Interview": "7/18/2018",
    "DOB": "04/30/1973",
    "Ethnicity": "BM",
    "Offense date": "09/21/1991",
    "Age at offense": "18",
    "Time served at interview": "26 years",
    "Id": "327614",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19941783637so2d114611277 Asked me about a pro bono attorney. Granted hearing but no date."
  },
  {
    "Full Name": "Kenneth Woodburn",
    "First Name": "Kenneth",
    "Last Name": "Woodburn",
    "Charge": "Second degree",
    "Interview": "7/19/2018",
    "DOB": "11/23/1973",
    "Ethnicity": "WM",
    "Offense date": "05/31/1992",
    "Age at offense": "18",
    "Time served at interview": "26 years",
    "Id": "330091",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19941906643so2d126311673 https://www.ipetitions.com/petition/buddy-woodburn"
  },
  {
    "Full Name": "Nadaedrick Campbell",
    "First Name": "Nadaedrick",
    "Last Name": "Campbell",
    "Charge": "First degree",
    "Interview": "7/19/2018",
    "DOB": "05/12/1972",
    "Ethnicity": "BM",
    "Offense date": "12/23/1992",
    "Age at offense": "20",
    "Time served at interview": "25 years",
    "Id": "357936",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19961985683so2d130211704 Victim police officer"
  },
  {
    "Full Name": "Ulysses Jones",
    "First Name": "Ulysses",
    "Last Name": "Jones",
    "Charge": "First degree",
    "Interview": "7/19/2018",
    "DOB": "10/09/1974",
    "Ethnicity": "BM",
    "Offense date": "10/05/1996",
    "Age at offense": "21",
    "Time served at interview": "21 years",
    "Id": "339308",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1031436.html Victim police officer"
  },
  {
    "Full Name": "Kendrick Fisher",
    "First Name": "Kendrick",
    "Last Name": "Fisher",
    "Charge": "Second degree",
    "Interview": "7/25/2018",
    "DOB": "06/07/1975",
    "Ethnicity": "BM",
    "Offense date": "02/20/1994",
    "Age at offense": "18",
    "Time served at interview": "24 years",
    "Id": "349524",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.courtlistener.com/opinion/1657258/state-v-fisher/ PARDON HEARING 10/15/2018. PAROLE ELIGIBLE AFTER 37.5 years"
  },
  {
    "Full Name": "Ralph Dawson",
    "First Name": "Ralph",
    "Last Name": "Dawson",
    "Charge": "Second degree",
    "Interview": "7/6/17 Reinterviewed 7/25/2018",
    "DOB": "06/15/1966",
    "Ethnicity": "WM",
    "Offense date": "09/08/1986",
    "Age at offense": "20",
    "Time served at interview": "31 years",
    "Id": "119851",
    "At launch": "",
    "Include": "",
    "Notes": "Pardon hearing 12/16/19"
  },
  {
    "Full Name": "Anthony Bascle",
    "First Name": "Anthony",
    "Last Name": "Bascle",
    "Charge": "First degree",
    "Interview": "7/26/2018",
    "DOB": "06/17/1974",
    "Ethnicity": "WM",
    "Offense date": "07/02/1995",
    "Age at offense": "21",
    "Time served at interview": "23 years",
    "Id": "383958",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1199557.html; https://www.gpo.gov/fdsys/pkg/USCOURTS-laed-2_07-cv- 09142/pdf/USCOURTS-laed-2_07-cv-09142-0.pdfCodefendant Emerson Simmons"
  },
  {
    "Full Name": "Terry Jones",
    "First Name": "Terry",
    "Last Name": "Jones",
    "Charge": "Second degree",
    "Interview": "7/27/2018",
    "DOB": "07/04/1973",
    "Ethnicity": "BM",
    "Offense date": "05/26/1995",
    "Age at offense": "21",
    "Time served at interview": "23 years",
    "Id": "",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.gpo.gov/fdsys/pkg/USCOURTS-laed-2_07-cv-03816/pdf/USCOURTS-laed-2_07-cv-03816-0.pdf"
  },
  {
    "Full Name": "Ricky Bennett",
    "First Name": "Ricky",
    "Last Name": "Bennett",
    "Charge": "Second degree",
    "Interview": "7/27/2018",
    "DOB": "12/02/1970",
    "Ethnicity": "BM",
    "Offense date": "12/07/1991",
    "Age at offense": "21",
    "Time served at interview": "26 years",
    "Id": "419642",
    "At launch": "",
    "Include": "",
    "Notes": "(Was apprehended a year after crime)"
  },
  {
    "Full Name": "Jeffrey Nelson",
    "First Name": "Jeffrey",
    "Last Name": "Nelson",
    "Charge": "First degree",
    "Interview": "8/14/2018",
    "DOB": "03/17/1976",
    "Ethnicity": "WM",
    "Offense date": "10/17/1995",
    "Age at offense": "21",
    "Time served at interview": "22 years",
    "Id": "382108",
    "At launch": "",
    "Include": "",
    "Notes": "PARDON HEARING 2/25/2019 Denied Victim Opposition"
  },
  {
    "Full Name": "Neal Spencer",
    "First Name": "Neal",
    "Last Name": "Spencer",
    "Charge": "Second degree",
    "Interview": "8/14/2018",
    "DOB": "07/01/1970",
    "Ethnicity": "BM",
    "Offense date": "06/06/1991",
    "Age at offense": "20",
    "Time served at interview": "27 years",
    "Id": "300641",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Elliott Guilbeau",
    "First Name": "Elliott",
    "Last Name": "Guilbeau",
    "Charge": "Second degree",
    "Interview": "8/15/2018",
    "DOB": "07/22/1967",
    "Ethnicity": "BM",
    "Offense date": "12/19/1987",
    "Age at offense": "20",
    "Time served at interview": "30 years",
    "Id": "129676",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.doc.la.gov/media/1/january.22.full.docket.pdfGRANTED CTO 99 years WITH PE AFTER 45 ON 1/22/18"
  },
  {
    "Full Name": "Frank Green",
    "First Name": "Frank",
    "Last Name": "Green",
    "Charge": "Second degree",
    "Interview": "8/15/2018",
    "DOB": "09/20/1968",
    "Ethnicity": "BM",
    "Offense date": "05/25/1989",
    "Age at offense": "20",
    "Time served at interview": "29 years",
    "Id": "131046",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.courtlistener.com/opinion/1768167/state-v-green/ PARDON HEARING 12/17/18 GRANTED"
  },
  {
    "Full Name": "Steven Garner",
    "First Name": "Steven",
    "Last Name": "Garner",
    "Charge": "Second degree",
    "Interview": "8/15/2018",
    "DOB": "04/15/1970",
    "Ethnicity": "BM",
    "Offense date": "11/06/1990",
    "Age at offense": "20",
    "Time served at interview": "27 years",
    "Id": "312935",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19931824621so2d120311685"
  },
  {
    "Full Name": "Melvin Davis",
    "First Name": "Melvin",
    "Last Name": "Davis",
    "Charge": "Second degree",
    "Interview": "8/15/2018",
    "DOB": "09/06/1973",
    "Ethnicity": "BM",
    "Offense date": "01/05/1994",
    "Age at offense": "20",
    "Time served at interview": "24 years",
    "Id": "314198",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Kendrick Howard",
    "First Name": "Kendrick",
    "Last Name": "Howard",
    "Charge": "First degree",
    "Interview": "8/29/2018",
    "DOB": "12/18/1973",
    "Ethnicity": "BM",
    "Offense date": "11/30/1993",
    "Age at offense": "19",
    "Time served at interview": "24 years",
    "Id": "371464",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1045723.html"
  },
  {
    "Full Name": "Patrick Johnson",
    "First Name": "Patrick",
    "Last Name": "Johnson",
    "Charge": "Second degree",
    "Interview": "8/29/2018",
    "DOB": "10/07/1973",
    "Ethnicity": "BM",
    "Offense date": "08/06/1992",
    "Age at offense": "18",
    "Time served at interview": "26 years",
    "Id": "336004",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1324534.html"
  },
  {
    "Full Name": "Albert Lavalais",
    "First Name": "Albert",
    "Last Name": "Lavalais",
    "Charge": "First degree",
    "Interview": "8/29/2018",
    "DOB": "07/28/1965",
    "Ethnicity": "BM",
    "Offense date": "02/12/1985 (Apprehended in 1995)",
    "Age at offense": "19",
    "Time served at interview": "23 years",
    "Id": "330949",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19961733685so2d104811483"
  },
  {
    "Full Name": "Chris Phillips",
    "First Name": "Chris",
    "Last Name": "Phillips",
    "Charge": "Second degree",
    "Interview": "8/30/2018",
    "DOB": "09/24/1974",
    "Ethnicity": "BM",
    "Offense date": "05/01/1993",
    "Age at offense": "18",
    "Time served at interview": "25 years",
    "Id": "314813",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Juan Matthews",
    "First Name": "Juan",
    "Last Name": "Matthews",
    "Charge": "Second degree",
    "Interview": "8/30/2018",
    "DOB": "08/03/1970",
    "Ethnicity": "BM",
    "Offense date": "03/31/1992",
    "Age at offense": "21",
    "Time served at interview": "26 years",
    "Id": "225702",
    "At launch": "",
    "Include": "",
    "Notes": "Innocence claim Granted a hearing but no date"
  },
  {
    "Full Name": "Wilfred Guy",
    "First Name": "Wilfred",
    "Last Name": "Guy",
    "Charge": "Second degree",
    "Interview": "8/30/2018",
    "DOB": "08/08/1966",
    "Ethnicity": "BM",
    "Offense date": "10/30/1982",
    "Age at offense": "18",
    "Time served at interview": "34 years",
    "Id": "111795",
    "At launch": "",
    "Include": "",
    "Notes": "Terrence Guy’s older brother"
  },
  {
    "Full Name": "Troy Andrews",
    "First Name": "Troy",
    "Last Name": "Andrews",
    "Charge": "First degree",
    "Interview": "8/30/2018",
    "DOB": "08/30/1974",
    "Ethnicity": "BM",
    "Offense date": "12/24/1995",
    "Age at offense": "21",
    "Time served at interview": "22 years",
    "Id": "406995",
    "At launch": "",
    "Include": "",
    "Notes": "https://cases.justia.com/louisiana/fourth-circuit-court-of-appeal/2001-2000-ka-1106.pdf?ts=1442005216 Codefendant Terry West Innocence Claim"
  },
  {
    "Full Name": "Jerry Williams",
    "First Name": "Jerry",
    "Last Name": "Williams",
    "Charge": "Second degree",
    "Interview": "8/30/2018",
    "DOB": "11/30/1958",
    "Ethnicity": "BM",
    "Offense date": "02/14/1977",
    "Age at offense": "18",
    "Time served at interview": "41 years",
    "Id": "85935",
    "At launch": "",
    "Include": "",
    "Notes": "GRANTED 5-0 CTO APRIL 2015; PAROLED OCTOBER 11, 2018.Wants to be reunited with his twin Terry."
  },
  {
    "Full Name": "Jerome Derricks",
    "First Name": "Jerome",
    "Last Name": "Derricks",
    "Charge": "Second degree",
    "Interview": "9/18/2018",
    "DOB": "09/18/1965",
    "Ethnicity": "BM",
    "Offense date": "01/26/1986",
    "Age at offense": "20",
    "Time served at interview": "32 years",
    "Id": "113381",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.wafb.com/story/35688133/gonzales-man-convicted-of-1986-brutal-murder-denied-parole/ DENIED PARDON BOARD 6/17/2017"
  },
  {
    "Full Name": "Isiah Diggs",
    "First Name": "Isiah",
    "Last Name": "Diggs",
    "Charge": "First degree",
    "Interview": "9/18/2018",
    "DOB": "04/16/1972",
    "Ethnicity": "BM",
    "Offense date": "10/30/1992",
    "Age at offense": "19",
    "Time served at interview": "25 years",
    "Id": "175552",
    "At launch": "",
    "Include": "",
    "Notes": "Innocence claim"
  },
  {
    "Full Name": "Kenneth Magee",
    "First Name": "Kenneth",
    "Last Name": "Magee",
    "Charge": "First degree",
    "Interview": "9/18/2018",
    "DOB": "02/07/1962",
    "Ethnicity": "BM",
    "Offense date": "10/18/1981",
    "Age at offense": "19",
    "Time served at interview": "36 years",
    "Id": "97408",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Donahue Smith",
    "First Name": "Donahue",
    "Last Name": "Smith",
    "Charge": "Second degree",
    "Interview": "9/19/2018",
    "DOB": "07/05/1970",
    "Ethnicity": "BM",
    "Offense date": "11/08/1991",
    "Age at offense": "21",
    "Time served at interview": "26 years",
    "Id": "333620",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "David Chenevert",
    "First Name": "David",
    "Last Name": "Chenevert",
    "Charge": "First degree",
    "Interview": "9/20/2018",
    "DOB": "07/04/1958",
    "Ethnicity": "WM",
    "Offense date": "09/28/1979",
    "Age at offense": "21",
    "Time served at interview": "39 years",
    "Id": "95250",
    "At launch": "",
    "Include": "",
    "Notes": "Plead https://abcnews.go.com/2020/US/story?id=1052747&page=1 Granted hearing, no date. Married to Sheila."
  },
  {
    "Full Name": "Michael Thomas",
    "First Name": "Michael",
    "Last Name": "Thomas",
    "Charge": "First degree",
    "Interview": "10/2/2018",
    "DOB": "04/03/1970",
    "Ethnicity": "WM",
    "Offense date": "05/16/1989",
    "Age at offense": "19",
    "Time served at interview": "29 years",
    "Id": "304718",
    "At launch": "",
    "Include": "",
    "Notes": "Couple in Church Point burglary"
  },
  {
    "Full Name": "Patrick Lucien",
    "First Name": "Patrick",
    "Last Name": "Lucien",
    "Charge": "Second degree",
    "Interview": "10/2/2018",
    "DOB": "07/19/1971",
    "Ethnicity": "BM",
    "Offense date": "12/21/1991",
    "Age at offense": "20",
    "Time served at interview": "26 years",
    "Id": "330864",
    "At launch": "",
    "Include": "",
    "Notes": "Lounge in Marrero"
  },
  {
    "Full Name": "Chadwick Tate",
    "First Name": "Chadwick",
    "Last Name": "Tate",
    "Charge": "Second degree",
    "Interview": "10/3/2018",
    "DOB": "08/24/1971",
    "Ethnicity": "BM",
    "Offense date": "02/21/1992",
    "Age at offense": "20",
    "Time served at interview": "26 years",
    "Id": "331176",
    "At launch": "",
    "Include": "",
    "Notes": "Innocence claim"
  },
  {
    "Full Name": "Dannie Johnson",
    "First Name": "Dannie",
    "Last Name": "Johnson",
    "Charge": "First degree",
    "Interview": "10/3/2018",
    "DOB": "03/10/1963",
    "Ethnicity": "BM",
    "Offense date": "02/05/1982",
    "Age at offense": "18",
    "Time served at interview": "36 years",
    "Id": "104404",
    "At launch": "",
    "Include": "",
    "Notes": "Fremin’s food store New Iberia"
  },
  {
    "Full Name": "Randy Thomas",
    "First Name": "Randy",
    "Last Name": "Thomas",
    "Charge": "Second degree",
    "Interview": "10/3/2018",
    "DOB": "05/14/1973",
    "Ethnicity": "BM",
    "Offense date": "06/10/1994",
    "Age at offense": "21",
    "Time served at interview": "24 years",
    "Id": "363647",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19961955683so2d127211677 Buford’s grocery robbery Shreveport. Was shot."
  },
  {
    "Full Name": "Levelle Tolliver",
    "First Name": "Levelle",
    "Last Name": "Tolliver",
    "Charge": "Second degree",
    "Interview": "10/3/2018",
    "DOB": "10/02/1972",
    "Ethnicity": "BM",
    "Offense date": "08/21/1993",
    "Age at offense": "20",
    "Time served at interview": "25 years",
    "Id": "406570",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/20001711753so2d95811493 Shooting after dice game"
  },
  {
    "Full Name": "Eric Taylor",
    "First Name": "Eric",
    "Last Name": "Taylor",
    "Charge": "Second degree",
    "Interview": "10/4/2018",
    "DOB": "08/26/1974",
    "Ethnicity": "BM",
    "Offense date": "01/21/1994",
    "Age at offense": "19 Served 36 years",
    "Time served at interview": "",
    "Id": "348365",
    "At launch": "",
    "Include": "",
    "Notes": "Circle K robbery"
  },
  {
    "Full Name": "Gordon Newman",
    "First Name": "Gordon",
    "Last Name": "Newman",
    "Charge": "First degree",
    "Interview": "10/4/2018",
    "DOB": "05/18/1976",
    "Ethnicity": "BM",
    "Offense date": "04/18/1995",
    "Age at offense": "18",
    "Time served at interview": "23 years",
    "Id": "471232",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1492307.html https://www.gpo.gov/fdsys/pkg/USCOURTS-laed-2_09-cv-04445/pdf/USCOURTS-laed-2_09-cv-04445-0.pdf"
  },
  {
    "Full Name": "Kennedy Thompson",
    "First Name": "Kennedy",
    "Last Name": "Thompson",
    "Charge": "Second degree",
    "Interview": "10/4/2018",
    "DOB": "02/11/1964",
    "Ethnicity": "BM",
    "Offense date": "01/27/1983",
    "Age at offense": "18",
    "Time served at interview": "35 years",
    "Id": "111476",
    "At launch": "",
    "Include": "",
    "Notes": "https://casetext.com/case/state-v-thompson-483Armed robbery, man died four days later in hospital (coma)"
  },
  {
    "Full Name": "Myron Smith",
    "First Name": "Myron",
    "Last Name": "Smith",
    "Charge": "First degree",
    "Interview": "11/14/2018",
    "DOB": "01/17/1974",
    "Ethnicity": "BM",
    "Offense date": "11/04/1995",
    "Age at offense": "21",
    "Time served at interview": "23 years",
    "Id": "396328",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19991415740so2d67511218Shreveport. With fellow Blood shot into a house thinking Crips inside. Crips gone; killed 14-year-old boy."
  },
  {
    "Full Name": "Solomon Birdsong",
    "First Name": "Solomon",
    "Last Name": "Birdsong",
    "Charge": "First degree",
    "Interview": "11/14/2018",
    "DOB": "09/05/1962",
    "Ethnicity": "BM",
    "Offense date": "02/02/1982",
    "Age at offense": "19",
    "Time served at interview": "36 years",
    "Id": "102863",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19841688452so2d123611431Shreveport. Robbed pizza hut and killed attendant. Used to work there. Son of high school principal. (15-year-old brother accomplice charges dropped)."
  },
  {
    "Full Name": "Cleothus Price",
    "First Name": "Cleothus",
    "Last Name": "Price",
    "Charge": "Second degree",
    "Interview": "11/15/2018",
    "DOB": "04/05/1975",
    "Ethnicity": "BM",
    "Offense date": "03/25/1996",
    "Age at offense": "20",
    "Time served at interview": "22 years",
    "Id": "398352",
    "At launch": "",
    "Include": "",
    "Notes": "Shooting in argument"
  },
  {
    "Full Name": "George Crawford",
    "First Name": "George",
    "Last Name": "Crawford",
    "Charge": "First degree",
    "Interview": "12/04/2018",
    "DOB": "05/09/1975",
    "Ethnicity": "BM",
    "Offense date": "09/22/1994",
    "Age at offense": "19",
    "Time served at interview": "24 years",
    "Id": "339214",
    "At launch": "",
    "Include": "",
    "Notes": "https://law.justia.com/cases/louisiana/fourth-circuit-court-of-appeal/2017/2017-k-0481.html https://cases.justia.com/louisiana/fourth-circuit-court-of-appeal/2003-2002-k-2048.pdf?ts=1439845218 http://www.ca5.uscourts.gov/opinions%5Cunpub%5C06/06-30892.0.wpd.pdf"
  },
  {
    "Full Name": "Winfred Davenport",
    "First Name": "Winfred",
    "Last Name": "Davenport",
    "Charge": "Second degree",
    "Interview": "12/04/2018",
    "DOB": "09/11/1975",
    "Ethnicity": "BM",
    "Offense date": "01/10/1996",
    "Age at offense": "20",
    "Time served at interview": "22 years",
    "Id": "390368",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1308130.html https://www.leagle.com/decision/19981236723so2d51311139 Codefendant Norman Dozier"
  },
  {
    "Full Name": "Steve Evans",
    "First Name": "Steve",
    "Last Name": "Evans",
    "Charge": "Second degree",
    "Interview": "12/04/2018",
    "DOB": "06/03/1973",
    "Ethnicity": "BM",
    "Offense date": "08/05/1993",
    "Age at offense": "20",
    "Time served at interview": "25 years",
    "Id": "312033",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19971975688so2d128711666 https://www.leagle.com/decision/19961214669so2d54511015 Codefendant Troy West"
  },
  {
    "Full Name": "Lawrence Peters",
    "First Name": "Lawrence",
    "Last Name": "Peters",
    "Charge": "Second degree",
    "Interview": "12/04/2018",
    "DOB": "06/12/1975",
    "Ethnicity": "BM",
    "Offense date": "07/16/1994",
    "Age at offense": "19",
    "Time served at interview": "24 years",
    "Id": "325716",
    "At launch": "",
    "Include": "",
    "Notes": "http://caselaw.findlaw.com/la-court-of-appeal/1042959.html Codefendant Manuel Nelson  JUVENILE OFFENDERS IN REDArticle on Juveniles and Montgomery: http://www.houmatoday.com/news/20160611/cases-up-for-review-under-montgomery-v- louisiana"
  },
  {
    "Full Name": "Jermaine Coates",
    "First Name": "Jermaine",
    "Last Name": "Coates",
    "Charge": "Second degree",
    "Interview": "7/24/2017",
    "DOB": "07/16/1979",
    "Ethnicity": "BM",
    "Offense date": "06/12/1995",
    "Age at offense": "15",
    "Time served at interview": "22 years",
    "Id": "366873",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Barry Pascual",
    "First Name": "Barry",
    "Last Name": "Pascual",
    "Charge": "First degree",
    "Interview": "7/27/2017",
    "DOB": "02/26/1979",
    "Ethnicity": "WM",
    "Offense date": "02/05/1996",
    "Age at offense": "16",
    "Time served at interview": "21 years",
    "Id": "390968",
    "At launch": "",
    "Include": "",
    "Notes": "http://caselaw.findlaw.com/la-court-of-appeal/1154172.html CODEFENDANT MADE PAROLE ELIGIBLE, BUT HE WAS DENIED BY DA."
  },
  {
    "Full Name": "Jeff Haggins",
    "First Name": "Jeff",
    "Last Name": "Haggins",
    "Charge": "Second degree",
    "Interview": "8/8/2017",
    "DOB": "12/08/1977",
    "Ethnicity": "BM",
    "Offense date": "09/10/1995",
    "Age at offense": "17",
    "Time served at interview": "21 years",
    "Id": "377590",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.iberianet.com/news/really-weird-case/article_e49f427e-d944-11e6-b5f2-bf7fe91f459c.html Transferred to Police Barracks."
  },
  {
    "Full Name": "Clifton Greene",
    "First Name": "Clifton",
    "Last Name": "Greene",
    "Charge": "First degree",
    "Interview": "6/13/2018",
    "DOB": "09/19/1975",
    "Ethnicity": "BM",
    "Offense date": "08/09/1993",
    "Age at offense": "17 (40 days before 18)",
    "Time served at interview": "24 years",
    "Id": "339979",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.courtlistener.com/opinion/1114684/state-v-green/ DENIED PAROLE 8/09/18"
  },
  {
    "Full Name": "Willie Plater",
    "First Name": "Willie",
    "Last Name": "Plater",
    "Charge": "First degree",
    "Interview": "6/13/2018",
    "DOB": "07/02/1975",
    "Ethnicity": "BM",
    "Offense date": "09/29/1992",
    "Age at offense": "17 (3 months before 18)",
    "Time served at interview": "25 years",
    "Id": "332913",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1860862.html https://www.leagle.com/decision/19951345661so2d68411107DENIED PAROLE 12/13/18 Victim opposition and write ups in 2016 Codefendant Frederick Thompson"
  },
  {
    "Full Name": "Terrance Simon",
    "First Name": "Terrance",
    "Last Name": "Simon",
    "Charge": "Second degree",
    "Interview": "6/13/2018",
    "DOB": "03/25/1976",
    "Ethnicity": "BM",
    "Offense date": "08/29/1993",
    "Age at offense": "17",
    "Time served at interview": "24 years",
    "Id": "344209",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19961771677so2d109411629"
  },
  {
    "Full Name": "Shon Williams",
    "First Name": "Shon",
    "Last Name": "Williams",
    "Charge": "Second degree",
    "Interview": "6/14/2018",
    "DOB": "03/17/1976",
    "Ethnicity": "BM",
    "Offense date": "05/27/1993",
    "Age at offense": "17",
    "Time served at interview": "25 years",
    "Id": "340730",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.nola.com/crime/index.ssf/2016/08/killer_at_17_parole_shon_willi.html"
  },
  {
    "Full Name": "Emerson Simmons",
    "First Name": "Emerson",
    "Last Name": "Simmons",
    "Charge": "Second degree",
    "Interview": "6/15/2018",
    "DOB": "08/03/1977",
    "Ethnicity": "WM",
    "Offense date": "07/02/1995",
    "Age at offense": "17 (30 days before 18)",
    "Time served at interview": "22 years",
    "Id": "387205",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1199557.html Codefendant Anthony Bascle PAROLED 12/13/2018"
  },
  {
    "Full Name": "Ronald Reynolds",
    "First Name": "Ronald",
    "Last Name": "Reynolds",
    "Charge": "Second degree",
    "Interview": "6/15/2018",
    "DOB": "02/26/1973",
    "Ethnicity": "BM",
    "Offense date": "02/08/1991",
    "Age at offense": "17 (18 days before 18)",
    "Time served at interview": "27 years",
    "Id": "326830",
    "At launch": "",
    "Include": "",
    "Notes": "Granted Habeas Corpus 2016.Parole Hearing 1/16/20"
  },
  {
    "Full Name": "Arthur Journet",
    "First Name": "Arthur",
    "Last Name": "Journet",
    "Charge": "Second degree",
    "Interview": "6/15/2018",
    "DOB": "04/02/1976",
    "Ethnicity": "BM",
    "Offense date": "07/11/1992",
    "Age at offense": "16 https://www.leagle.com/decision/19932016629so2d138711451",
    "Time served at interview": "25 years",
    "Id": "322651",
    "At launch": "",
    "Include": "",
    "Notes": "PAROLED 8/9/2018"
  },
  {
    "Full Name": "Steve Perkins",
    "First Name": "Steve",
    "Last Name": "Perkins",
    "Charge": "First degree",
    "Interview": "6/20/18",
    "DOB": "07/10/1957",
    "Ethnicity": "BM",
    "Offense date": "12/20/1974",
    "Age at offense": "17",
    "Time served at interview": "43 years",
    "Id": "84540",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19761634340so2d129411378 PAROLED 7/31/2018"
  },
  {
    "Full Name": "Warren Palmer",
    "First Name": "Warren",
    "Last Name": "Palmer",
    "Charge": "Second degree",
    "Interview": "6/20/2018",
    "DOB": "09/06/1974",
    "Ethnicity": "BM",
    "Offense date": "03/16/1992",
    "Age at offense": "17",
    "Time served at interview": "26 years",
    "Id": "318473",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/infdco20160506b67 DENIED PAROLE 7/31/2018 Escape attempt"
  },
  {
    "Full Name": "Henry Montgomery",
    "First Name": "Henry",
    "Last Name": "Montgomery",
    "Charge": "First degree",
    "Interview": "6/26/2018",
    "DOB": "06/17/1946",
    "Ethnicity": "BM",
    "Offense date": "11/13/1963",
    "Age at offense": "17",
    "Time served at interview": "54 years",
    "Id": "71240",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-supreme-court/1740241.html DENIED PAROLE 2/17/2018 Kuhn and again 3/19"
  },
  {
    "Full Name": "Johnny Powell",
    "First Name": "Johnny",
    "Last Name": "Powell",
    "Charge": "Second degree",
    "Interview": "6/26/2018",
    "DOB": "03/14/1976",
    "Ethnicity": "BM",
    "Offense date": "05/09/1993",
    "Age at offense": "17",
    "Time served at interview": "25 years",
    "Id": "336696",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19951164671so2d49311051 PAROLED 12/13/2018"
  },
  {
    "Full Name": "Frederick Thompson",
    "First Name": "Frederick",
    "Last Name": "Thompson",
    "Charge": "First degree",
    "Interview": "6/26/2018",
    "DOB": "09/01/1975",
    "Ethnicity": "BM",
    "Offense date": "09/20/1992",
    "Age at offense": "17",
    "Time served at interview": "25 years",
    "Id": "330737",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/19951345661so2d68411107 He was the primary codefendant of Willie Plater."
  },
  {
    "Full Name": "Shawn Toussaint",
    "First Name": "Shawn",
    "Last Name": "Toussaint",
    "Charge": "Second degree",
    "Interview": "6/26/2018",
    "DOB": "08/26/1979",
    "Ethnicity": "BM",
    "Offense date": "05/08/1997",
    "Age at offense": "17",
    "Time served at interview": "21 years",
    "Id": "384865",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1324222.html"
  },
  {
    "Full Name": "Troy Young",
    "First Name": "Troy",
    "Last Name": "Young",
    "Charge": "Second degree",
    "Interview": "6/26/2018",
    "DOB": "09/02/1976",
    "Ethnicity": "BM",
    "Offense date": "02/28/1994",
    "Age at offense": "17",
    "Time served at interview": "24 years",
    "Id": "346152",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.dailycomet.com/news/20170811/hearings-delayed-in-decades-old-murder-cases Shawn Arcement codefendant.PAROLE DATE 3/12/2019 denied"
  },
  {
    "Full Name": "Curt Alonzo",
    "First Name": "Curt",
    "Last Name": "Alonzo",
    "Charge": "Second degree",
    "Interview": "6/27/2018",
    "DOB": "08/02/1974",
    "Ethnicity": "BM",
    "Offense date": "07/12/1992",
    "Age at offense": "17 (20 days before 18)",
    "Time served at interview": "24 years",
    "Id": "329528",
    "At launch": "",
    "Include": "",
    "Notes": "PAROLED 7/10/2018"
  },
  {
    "Full Name": "Shawn Arcement",
    "First Name": "Shawn",
    "Last Name": "Arcement",
    "Charge": "Second degree",
    "Interview": "6/28/2018",
    "DOB": "09/27/1976",
    "Ethnicity": "BM",
    "Offense date": "02/28/1994",
    "Age at offense": "17",
    "Time served at interview": "24 years",
    "Id": "346154",
    "At launch": "",
    "Include": "",
    "Notes": "http://www.dailycomet.com/news/20170811/hearings-delayed-in-decades-old-murder-cases Codefendant with Troy Young."
  },
  {
    "Full Name": "Field Calhoun",
    "First Name": "Field",
    "Last Name": "Calhoun",
    "Charge": "First degree",
    "Interview": "6/28/2018",
    "DOB": "05/09/1969",
    "Ethnicity": "BM",
    "Offense date": "12/20/1986",
    "Age at offense": "17",
    "Time served at interview": "31 years",
    "Id": "124382",
    "At launch": "",
    "Include": "",
    "Notes": "DENIED by Parole Board 8/15/19"
  },
  {
    "Full Name": "Chakha James",
    "First Name": "Chakha",
    "Last Name": "James",
    "Charge": "Second degree",
    "Interview": "6/28/2018",
    "DOB": "02/10/1978",
    "Ethnicity": "BM",
    "Offense date": "05/27/1995",
    "Age at offense": "17",
    "Time served at interview": "23 years",
    "Id": "409338",
    "At launch": "",
    "Include": "",
    "Notes": "Parole hearing date 1/16/20"
  },
  {
    "Full Name": "Willie Williams",
    "First Name": "Willie",
    "Last Name": "Williams",
    "Charge": "Second degree",
    "Interview": "6/28/2018",
    "DOB": "02/10/1978",
    "Ethnicity": "BM",
    "Offense date": "07/18/1995",
    "Age at offense": "17",
    "Time served at interview": "23 years",
    "Id": "372074",
    "At launch": "",
    "Include": "",
    "Notes": ""
  },
  {
    "Full Name": "Fabian Harper",
    "First Name": "Fabian",
    "Last Name": "Harper",
    "Charge": "Second degree",
    "Interview": "7/26/2018",
    "DOB": "09/08/1973",
    "Ethnicity": "BM",
    "Offense date": "09/05/1990",
    "Age at offense": "16",
    "Time served at interview": "27 years",
    "Id": "336374",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1870217.html https://www.leagle.com/decision/19951197660so2d5371974 PAROLED 10/2/2018"
  },
  {
    "Full Name": "Ronald Olivier",
    "First Name": "Ronald",
    "Last Name": "Olivier",
    "Charge": "Second degree",
    "Interview": "7/26/2018",
    "DOB": "03/10/1975",
    "Ethnicity": "BM",
    "Offense date": "12/25/1991",
    "Age at offense": "16",
    "Time served at interview": "26 years",
    "Id": "323933",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1889927.html https://www.gpo.gov/fdsys/pkg/USCOURTS-laed-2_14-cv-02773/pdf/USCOURTS-laed-2_14-cv-02773-1.pdf PAROLED 11/8/2018"
  },
  {
    "Full Name": "Jameel Malik",
    "First Name": "Jameel",
    "Last Name": "Malik",
    "Charge": "Second degree",
    "Interview": "7/26/2018",
    "DOB": "01/17/1976",
    "Ethnicity": "BM",
    "Offense date": "10/04/1993",
    "Age at offense": "17",
    "Time served at interview": "24 years",
    "Id": "344888",
    "At launch": "",
    "Include": "",
    "Notes": "Plead case, was denied Habeas Corpus"
  },
  {
    "Full Name": "Dwight Jenkins",
    "First Name": "Dwight",
    "Last Name": "Jenkins",
    "Charge": "Second degree",
    "Interview": "7/27/2018",
    "DOB": "12/15/1971",
    "Ethnicity": "BM",
    "Offense date": "02/14/1988",
    "Age at offense": "16",
    "Time served at interview": "30 years",
    "Id": "126109",
    "At launch": "",
    "Include": "",
    "Notes": "https://www.leagle.com/decision/1990601569so2d321592"
  },
  {
    "Full Name": "Melvin Mingo",
    "First Name": "Melvin",
    "Last Name": "Mingo",
    "Charge": "Second degree",
    "Interview": "8/16/2018",
    "DOB": "02/07/1978",
    "Ethnicity": "BM",
    "Offense date": "10/03/1994",
    "Age at offense": "16",
    "Time served at interview": "23 years",
    "Id": "367430",
    "At launch": "",
    "Include": "",
    "Notes": "With twin - Calvin."
  },
  {
    "Full Name": "Lawrence Jacobs",
    "First Name": "Lawrence",
    "Last Name": "Jacobs",
    "Charge": "Second degree",
    "Interview": "8/16/2018",
    "DOB": "11/07/1979",
    "Ethnicity": "BM",
    "Offense date": "10/31/1996",
    "Age at offense": "16",
    "Time served at interview": "21 years",
    "Id": "382521",
    "At launch": "",
    "Include": "",
    "Notes": "https://caselaw.findlaw.com/la-court-of-appeal/1568779.html BEN COHEN’S CLIENT. DENIED BY DA."
  },
  {
    "Full Name": "Troy Shelvin",
    "First Name": "Troy",
    "Last Name": "Shelvin",
    "Charge": "Second degree",
    "Interview": "11/13/2018",
    "DOB": "11/09/1970",
    "Ethnicity": "BM",
    "Offense date": "10/02/1988",
    "Age at offense": "17",
    "Time served at interview": "30 years",
    "Id": "293155",
    "At launch": "",
    "Include": "",
    "Notes": "DENIED PAROLE 12/13/18 Write ups"
  },
  {
    "Full Name": "Clifford Hampton",
    "First Name": "Clifford",
    "Last Name": "Hampton",
    "Charge": "Second degree",
    "Interview": "11/14/2018",
    "DOB": "02/12/1941",
    "Ethnicity": "BM",
    "Offense date": "1959, then killed another inmate on 10/21/1961",
    "Age at offense": "20 / 17",
    "Time served at interview": "59 years",
    "Id": "62167",
    "At launch": "",
    "Include": "",
    "Notes": "Paroled 3/19 Anna Lelelid’s client on the same day Montgomery was denied."
  },
  {
    "Full Name": "George Gillam",
    "First Name": "George",
    "Last Name": "Gillam",
    "Charge": "Second degree",
    "Interview": "11/15/2018",
    "DOB": "05/07/1977",
    "Ethnicity": "BM",
    "Offense date": "04/23/1994",
    "Age at offense": "16",
    "Time served at interview": "24 years",
    "Id": "392825",
    "At launch": "",
    "Include": "",
    "Notes": "PAROLED 11/8/2018, released April 2019"
  },
  {
    "Full Name": "Eric Matthews",
    "First Name": "Eric",
    "Last Name": "Matthews",
    "Charge": "First degree",
    "Interview": "8/14/17",
    "DOB": "01/17/1973",
    "Ethnicity": "BM",
    "Offense date": "05/12/1994",
    "Age at offense": "21",
    "Time served at interview": "23 years",
    "Id": "344887",
    "At launch": "no",
    "Include": "no",
    "Notes": "CONCERN ABOUT THE CRIME Met his parents at LIFE summit 9/26/19"
  },
  {
    "Full Name": "Gregory Savage",
    "First Name": "Gregory",
    "Last Name": "Savage",
    "Charge": "Second degree",
    "Interview": "7/25/17",
    "DOB": "02/23/1963",
    "Ethnicity": "BM",
    "Offense date": "06/02/1987",
    "Age at offense": "24",
    "Time served at interview": "30 years",
    "Id": "127336",
    "At launch": "no",
    "Include": "no",
    "Notes": "https://www.courtlistener.com/opinion/1839297/state-v-savage/CONCERN ABOUT THE CRIME"
  },
  {
    "Full Name": "Roney Womack",
    "First Name": "Roney",
    "Last Name": "Womack",
    "Charge": "Second degree",
    "Interview": "7/25/17",
    "DOB": "03/17/1969",
    "Ethnicity": "WM",
    "Offense date": "10/13/1988",
    "Age at offense": "19",
    "Time served at interview": "28 years",
    "Id": "131946",
    "At launch": "no",
    "Include": "no",
    "Notes": "http://www.leagle.com/decision/19911464592So2d872_11313/STATE v. WOMACKCONCERN ABOUT THE CRIME Granted a hearing but no date"
  },
  {
    "Full Name": "Kirt Hall",
    "First Name": "Kirt",
    "Last Name": "Hall",
    "Charge": "Second degree",
    "Interview": "7/18/17",
    "DOB": "12/23/1973",
    "Ethnicity": "BM",
    "Offense date": "02/17/1992",
    "Age at offense": "18",
    "Time served at interview": "25 years",
    "Id": "316858",
    "At launch": "no",
    "Include": "no",
    "Notes": "CONCERN ABOUT HIS PRESENTATION OF SELF FOR THIS PROJECT"
  },
  {
    "Full Name": "Berwick Redmond",
    "First Name": "Berwick",
    "Last Name": "Redmond",
    "Charge": "First degree",
    "Interview": "8/15/17",
    "DOB": "02/03/1970",
    "Ethnicity": "BM",
    "Offense date": "12/20/1990",
    "Age at offense": "20",
    "Time served at interview": "26 years",
    "Id": "287897",
    "At launch": "no",
    "Include": "no",
    "Notes": "CONCERN ABOUT THE CRIME"
  },
  {
    "Full Name": "Terrance Knox",
    "First Name": "Terrance",
    "Last Name": "Knox",
    "Charge": "Second degree",
    "Interview": "6/14/2018",
    "DOB": "02/18/1976",
    "Ethnicity": "BM",
    "Offense date": "09/28/1994",
    "Age at offense": "19",
    "Time served at interview": "23 years",
    "Id": "345888",
    "At launch": "no",
    "Include": "no",
    "Notes": "FLAT interview (I THINK HE WAS HIGH)"
  },
  {
    "Full Name": "Jason Baudoin",
    "First Name": "Jason",
    "Last Name": "Baudoin",
    "Charge": "First degree",
    "Interview": "7/27/2018",
    "DOB": "02/01/1978",
    "Ethnicity": "BM",
    "Offense date": "08/15/1997",
    "Age at offense": "19",
    "Time served at interview": "20 years",
    "Id": "402547",
    "At launch": "no",
    "Include": "no",
    "Notes": "FLAT interview"
  },
  {
    "Full Name": "Phil Banks",
    "First Name": "Phil",
    "Last Name": "Banks",
    "Charge": "Second degree",
    "Interview": "8/14/2018",
    "DOB": "04/16/1973",
    "Ethnicity": "BM",
    "Offense date": "07/15/1994",
    "Age at offense": "21",
    "Time served at interview": "24 years",
    "Id": "396166",
    "At launch": "no",
    "Include": "no",
    "Notes": "FLAT interview"
  },
  {
    "Full Name": "Reinier Neslo",
    "First Name": "Reinier",
    "Last Name": "Neslo",
    "Charge": "First degree",
    "Interview": "8/29/2018",
    "DOB": "01/30/1959",
    "Ethnicity": "BM",
    "Offense date": "12/16/1980",
    "Age at offense": "21",
    "Time served at interview": "37 years",
    "Id": "95210",
    "At launch": "no",
    "Include": "no",
    "Notes": "https://law.justia.com/cases/louisiana/supreme-court/1983/81-ka-1202-1.html CONCERN ABOUT CRIME and his account of it."
  },
  {
    "Full Name": "Adam Comeaux",
    "First Name": "Adam",
    "Last Name": "Comeaux",
    "Charge": "First degree",
    "Interview": "11/13/2018",
    "DOB": "12/07/1967",
    "Ethnicity": "BM",
    "Offense date": "09/01/1985",
    "Age at offense": "17",
    "Time served at interview": "33 years",
    "Id": "112373",
    "At launch": "no",
    "Include": "no",
    "Notes": "Death Row. Mentally disabled juvenile. Rape/Murder white victims https://www.courtlistener.com/opinion/1896775/state-v-comeaux/ https://law.justia.com/cases/louisiana/third-circuit-court-of-appeal/2018/ka-17-0682.html DO NOT INCLUDE. SHOULD HAVE BEEN SCREENED OUT FOR NATURE OF CRIME"
  }
]