import React, { lazy } from "react"

//const OtherComponent = React.'./OtherComponent'));

const registry = {
  aaron_brent: "./transcripts/aaron_brent.json",
  adonis_brooks: "./transcripts/adonis_brooks.json",
  albert_lavalais: "./transcripts/albert_lavalais.json",
  allen_pharr: "./transcripts/allen_pharr.json",
  alvin_catchings: "./transcripts/alvin_catchings.json",
  anthony_bascle: "./transcripts/anthony_bascle.json",
  anthony_hingle: "./transcripts/anthony_hingle.json",
  archie_tyner: "./transcripts/archie_tyner.json",
  arthur_carter: "./transcripts/arthur_carter.json",
  chadwick_tate: "./transcripts/chadwick_tate.json",
  charles_amos: "./transcripts/charles_amos.json",
  chris_montague: "./transcripts/chris_montague.json",
  chris_phillips: "./transcripts/chris_phillips.json",
  chuck_unger: "./transcripts/chuck_unger.json",
  cleothus_price: "./transcripts/cleothus_price.json",
  dannie_johnson: "./transcripts/dannie_johnson.json",
  danny_sermon: "./transcripts/danny_sermon.json",
  darnell_craft: "./transcripts/darnell_craft.json",
  darren_james: "./transcripts/darren_james.json",
  darwin_willie: "./transcripts/darwin_willie.json",
  daryl_evans: "./transcripts/daryl_evans.json",
  daryl_waters: "./transcripts/daryl_waters.json",
  david_chenevert: "./transcripts/david_chenevert.json",
  donahue_smith: "./transcripts/donahue_smith.json",
  edbert_simmons: "./transcripts/edbert_simmons.json",
  elliott_guilbeau: "./transcripts/elliott_guilbeau.json",
  eric_taylor: "./transcripts/eric_taylor.json",
  ernest_mcgee: "./transcripts/ernest_mcgee.json",
  everett_offray: "./transcripts/everett_offray.json",
  frank_green: "./transcripts/frank_green.json",
  george_crawford: "./transcripts/george_crawford.json",
  gordon_newman: "./transcripts/gordon_newman.json",
  gregory_alcindor: "./transcripts/gregory_alcindor.json",
  hannibal_stanfield: lazy(() =>
    import("./transcripts/hannibal_stanfield.json")
  ),
  hayward_jones: "./transcripts/hayward_jones.json",
  isaiah_diggs: "./transcripts/isaiah_diggs.json",
  jack_segura: "./transcripts/jack_segura.json",
  james_refuge: "./transcripts/james_refuge.json",
  jared_lanclow: "./transcripts/jared_lanclow.json",
  jeffrey_hillburn: "./transcripts/jeffrey_hillburn.json",
  jeffrey_nelson: "./transcripts/jeffrey_nelson.json",
  jerome_derricks: "./transcripts/jerome_derricks.json",
  jerry_brown: "./transcripts/jerry_brown.json",
  jerry_lewis: "./transcripts/jerry_lewis.json",
  jerry_williams: "./transcripts/jerry_williams.json",
  jimmy_robinson: "./transcripts/jimmy_robinson.json",
  jimmy_williams: "./transcripts/jimmy_williams.json",
  john_sheehan: "./transcripts/john_sheehan.json",
  juan_matthews: "./transcripts/juan_matthews.json",
  julius_holden: "./transcripts/julius_holden.json",
  keith_byes: "./transcripts/keith_byes.json",
  kendrick_fisher: "./transcripts/kendrick_fisher.json",
  kendrick_howard: "./transcripts/kendrick_howard.json",
  kennedy_thompson: "./transcripts/kennedy_thompson.json",
  kenneth_hill: "./transcripts/kenneth_hill.json",
  kenneth_mcgee: "./transcripts/kenneth_mcgee.json",
  kenneth_woodburn: "./transcripts/kenneth_woodburn.json",
  kevin_king: "./transcripts/kevin_king.json",
  kirt_hall: "./transcripts/kirt_hall.json",
  kuantau_reedertranscription: lazy(() =>
    import("./transcripts/kuantau_reeder.json")
  ),
  lawrence_kelly: "./transcripts/lawrence_kelly.json",
  lawrence_peters: "./transcripts/lawrence_peters.json",
  lawson_strickland: "./transcripts/lawson_strickland.json",
  levelle_tolliver: "./transcripts/levelle_tolliver.json",
  manuel_nelson: "./transcripts/manuel_nelson.json",
  marcus_artis: "./transcripts/marcus_artis.json",
  melvin_davis: "./transcripts/melvin_davis.json",
  merlin_renard: "./transcripts/merlin_renard.json",
  michael_doggett: "./transcripts/michael_doggett.json",
  michael_thomas: "./transcripts/michael_thomas.json",
  monte_white: "./transcripts/monte_white.json",
  myron_smith: "./transcripts/myron_smith.json",
  nadaedrick_campbell: lazy(() =>
    import("./transcripts/nadaedrick_campbell.json")
  ),
  neal_spencer: "./transcripts/neal_spencer.json",
  norman_dozier: "./transcripts/norman_dozier.json",
  patrick_johnson: "./transcripts/patrick_johnson.json",
  patrick_lucien: "./transcripts/patrick_lucien.json",
  paul_mayho: "./transcripts/paul_mayho.json",
  ralph_dawson: "./transcripts/ralph_dawson.json",
  randy_thomas: "./transcripts/randy_thomas.json",
  raymond_flank: "./transcripts/raymond_flank.json",
  ricky_bennett: "./transcripts/ricky_bennett.json",
  robert_juarbe: "./transcripts/robert_juarbe.json",
  ron_hicks: "./transcripts/ron_hicks.json",
  ron_wiggins: "./transcripts/ron_wiggins.json",
  sammie_robinson: "./transcripts/sammie_robinson.json",
  shawn_gaspard: "./transcripts/shawn_gaspard.json",
  sherman_singleton_mix: lazy(() =>
    import("./transcripts/sherman_singleton.json")
  ),
  sidney_anderson: "./transcripts/sidney_anderson.json",
  solomon_birdsong: "./transcripts/solomon_birdsong.json",
  steve_evans: "./transcripts/steve_evans.json",
  steven_garner: "./transcripts/steven_garner.json",
  surge_sherman: "./transcripts/surge_sherman.json",
  terrence_guy: "./transcripts/terrence_guy.json",
  terry_jones: "./transcripts/terry_jones.json",
  terry_pierce_mix: "./transcripts/terry_pierce.json",
  terry_west: "./transcripts/terry_west.json",
  theortric_givens: "./transcripts/theortric_givens.json",
  tommy_cage: "./transcripts/tommy_cage.json",
  tommy_floyd: "./transcripts/tommy_floyd.json",
  troy_andrews: "./transcripts/troy_andrews.json",
  troy_west: "./transcripts/troy_west.json",
  vashon_kelly: "./transcripts/vashon_kelly.json",
  walter_goodwin: "./transcripts/walter_goodwin.json",
  walter_reed: "./transcripts/walter_reed.json",
  wilford_guy: "./transcripts/wilford_guy.json",
  william_hall: "./transcripts/william_hall.json",
  winfred_davenport: "./transcripts/winfred_davenport.json",
}

export default registry
